import { ArrowLeft, CheckCircle2, Info, Mic2, Piano, Usb, Volume2 } from 'lucide-react';
import { usePitchDetector } from '../hooks/usePitchDetector';
import { pianoNoteLabel } from '../piano';
import type { PianoConfig } from '../types';

export function PianoInputPage({ piano, onBack }: { piano: PianoConfig; onBack: () => void }) {
  const detector = usePitchDetector();
  return <main className="page-content piano-input-page"><button type="button" className="back-link" onClick={() => { detector.stop(); onBack(); }}><ArrowLeft /> Retour</button><header className="page-heading"><span className="eyebrow">Diagnostic piano</span><h1>Entrée et justesse.</h1><p>Vérifie que Soufflet reçoit bien les notes avant une séance. Pour un piano acoustique, l’accordage mécanique doit rester confié à un technicien.</p></header><section className="piano-input-diagnostic"><article className={detector.status === 'listening' ? 'is-listening' : ''}><Mic2 /><small>Microphone monophonique</small><strong>{detector.reading ? pianoNoteLabel(detector.reading.midi, piano.notation) : '—'}</strong><span>{detector.reading ? `${detector.reading.cents > 0 ? '+' : ''}${detector.reading.cents} cents · confiance ${Math.round(detector.reading.confidence * 100)}%` : 'Joue une note tenue et isolée'}</span><button type="button" className="primary-button" onClick={() => detector.status === 'listening' ? detector.stop() : void detector.start()}>{detector.status === 'listening' ? <Volume2 /> : <Mic2 />}{detector.status === 'listening' ? 'Arrêter l’écoute' : 'Tester le microphone'}</button>{detector.error && <p>{detector.error}</p>}</article><article><Usb /><small>Entrée recommandée</small><strong>MIDI</strong><span>Reconnaît les vélocités, accords et deux mains sans bruit ambiant.</span><div><CheckCircle2 /> Sélectionne « Connecter MIDI » dans le lecteur, puis joue une touche.</div><div><Info /> Sur Android, un adaptateur USB OTG peut être nécessaire.</div></article><article><Piano /><small>Configuration active</small><strong>{piano.keyboardSize} touches</strong><span>{piano.name}</span><div><CheckCircle2 /> Conservée dans ton compte et reprise sur tes autres appareils.</div></article></section></main>;
}
